### PR TITLE
fix #143 - Still issues in unrolled list

### LINKED ISSUE #143: Still issues in unrolled list
> containers/src/containers/unrolledlist.d(403): Error: cannot implicitly convert expression llvm_cttz((*current).registry, true) of type inout(ulong) to uint
dsymbol/src/dsymbol/conversion/first.d(1176): Error: template instance `containers.unrolledlist.UnrolledList!(ubyte, Mallocator, false, 64u).UnrolledList.opSlice!(const(UnrolledList!(ubyte, Mallocator, false, 64u)))` error instantiating
containers/src/containers/unrolledlist.d(403): Error: cannot implicitly convert expression llvm_cttz((*current).registry, true) of type inout(ulong) to uint
dsymbol/src/dsymbol/conversion/first.d(1214): Error: template instance `containers.unrolledlist.UnrolledList!(ubyte, Mallocator, false, 64u).UnrolledList.opSlice!(UnrolledList!(ubyte, Mallocator, false, 64u))` error instantiating
containers/src/containers/unrolledlist.d(258): Error: cannot implicitly convert expression llvm_cttz((*this._front).registry, true) of type ulong to uint
containers/src/containers/unrolledlist.d(323): Error: cannot implicitly convert expression index of type immutable(ulong) to uint
dsymbol/src/dsymbol/conversion/first.d(1252): Error: template instance `containers.unrolledlist.UnrolledList!(ubyte, Mallocator, false, 64u)` error instantiating

[log file](https://travis-ci.org/dlang-community/DCD/jobs/521692949#L318)

### PR DESCRIPTION
**Pull request by Basile-z**

### CODE REVIEW

**Comment by Basile-z** [comment]
confirmed to fix the release process of DCD. The problem appeared even when compiling with -m32 for linux.

**Comment by WebFreak001** [comment]
https://github.com/dlang-community/containers/blob/master/src/containers/internal/backwards.d#L6

popcnt returns int but expects a ulong, the llvm_cttz function seems to accept a T as parameter and returns a T, so for a ulong it returns a ulong. Wouldn't it make more sense to keep it in for 32 bit but cast where needed?

**Comment by Basile-z** [comment]
I don't know actually this was just for DCD since i don't care about the 32 bit platform and in this case its performances.

**Comment by Basile-z** [comment]
In the absence of a better solution

**Comment by Basile-z** [comment]
In the absence of objection.

**Pull request merged**
