### PR TITLE
fix: UnrolledList calls constructors only once on clear

### LINKED ISSUE #168: segfault with HashMap of RefCounted!HashMap
```
import containers;
import std.typecons;

struct Map
{
    HashMap!(int, int) theMap;
}

unittest
{
    HashMap!(int, RefCounted!Map) mapOfMaps;
    foreach (i; 0 .. 1000)
    {
        RefCounted!Map val;
        val.theMap.getOrAdd(i, i);
        mapOfMaps.getOrAdd(i, val);
    }
}
```

This segfaults on HashMap.rehash()

### PR DESCRIPTION
**Pull request by Panke**
Fixes #168

### CODE REVIEW

**Comment by Imperatorn** [comment]
> Fixes #168

https://travis-ci.org/github/dlang-community/containers/builds/769485926

**Comment by Panke** [comment]
Tests work, that's a problem in stdx.allocator.

**Comment by rikkimax** [comment]
Can you please rebase so that we can trigger the CI?

**Review by CyberShadow — APPROVED** [review]
LGTM; rebased

**Pull request merged**
