### PR TITLE
Convert dub.json to dub.sdl, update stdx-allocator to 2.77.5 and set targetPath

### PR DESCRIPTION
**Pull request by PetarKirov**

### CODE REVIEW

**Comment by PetarKirov** [comment]
I working on tracking down the CI failure.

**Comment by andre2007** [comment]
@PetarKirov I close and reopen the pull request to restart the test pipeline.

**Comment by PetarKirov** [comment]
@andre2007 Thanks! When I was worked on this, I had problems related to Meson, which I couldn't reproduce locally, even in a Docker container.

**Comment by PetarKirov** [comment]
Hmm, seems to work. Alright then, merging.

**Pull request merged**
