### PR TITLE
CI fix rollup

### PR DESCRIPTION
**Pull request by CyberShadow**
Octopus merge of #173, #178 and #179 to test if this fixes CI.

### CODE REVIEW

**Comment by CyberShadow** [comment]
It's green!

**Comment by CyberShadow** [comment]
I tried swapping out #173 for #166, but it failed. #173 seems contentious but there are merits to it as well (no dependencies, no need to depend on packages owned by third parties; and, it doesn't look like std.experimental.allocator is running anywhere anyway).

**Comment by CyberShadow** [comment]
@PetarKirov @rikkimax What do you think, OK to move forward with this?

**Comment by rikkimax** [comment]
24 hours unless anyone objects, I'll merge.

**Comment by rikkimax** [comment]
Ah huh, found where travis was still being required, removed but it'll be a manual merge.

**Comment by CyberShadow** [comment]
> Ah huh, found where travis was still being required, removed but it'll be a manual merge.

It's here:

https://github.com/dlang-community/containers/settings/branch_protection_rules/1443434

Not sure what was changed but Travis was still in that list. I removed it and added GitHub Actions for DMD.

**Pull request merged**
