### PR TITLE
containers.hashmap: Re-add opApply iteration

### PR DESCRIPTION
**Pull request by CyberShadow**
Commit 15eea7fbc89f073838d14d86d47c1247dbe8c3a1 intentionally removed `opApply` iteration to make room for range-based iteration via `opSlice`. The change caused code breakage (`foreach (k, v; aa)` was broken as ranges, in lieu of language tuples, can only iterate as a `KeyValue` struct at best). That wouldn't be so bad by itself assuming the iterator range was implemented by keeping a pointer to the `HashMap` node and allowing writing back to it / accessing the value by reference... but, no, the `KeyValue` object used here actually created wasteful copies of iterated keys/values.

Furthermore, the new implementation of iteration accepted the following code:

```d
foreach (ref v; map) v++;
```

... which compiled, but did not actually mutate the iterated hashmap.

Improve the situation by adding `opApply` iteration back, thus unbreaking:

- iterating by key/value as distinct `foreach` parameters
- avoiding copying the key/value by providing it by `ref`
- writing values back to the `HashMap`.

### CODE REVIEW

**Comment by BBasile** [comment]
Can you see this: https://github.com/orgs/dlang-community/teams/all/discussions/3 ? I'm gonna say that you can do something like 

```d
void keyValueFunc(K, V)(ref K k,ref V v){}  
aa.byKeyValue.each!(a => keyValueFunc(a.key, a.value));
```

since opApply calls a delegate anyway.

> writing values back to the HashMap.

Yes maybe this is valid.

So you'll have to wait for @Hackerpilot's decision.

**Comment by CyberShadow** [comment]
> Can you see this: https://github.com/orgs/dlang-community/teams/all/discussions/3 ?

No, 404 for me.

> I'm gonna say that you can do something like

No, that won't work because - as mentioned above - the `byKeyValue` iterator *copies* the values into the struct it returns, so any `ref` is useless at this point.

Also, the `each` predicate in your code is missing `ref`, but even if you add it, it still won't change the above.

**Comment by Hackerpilot** [comment]
> No, 404 for me.

I invited you to the dlang-community org. The link should work now.

**Comment by Hackerpilot** [comment]
I tagged a new release with this change in it.

**Comment by CyberShadow** [comment]
Thank you!

**Pull request merged**
